### ISSUE TITLE
Scroll bar issue

### ISSUE THREAD

**Issue by ThibSab** [fk/masonite#34]
Hi,

Since this week, news scrollbars appeared on all my Tumblr post,
I'm using your theme, I looked on the CSS but I cannot find how to delete them.
Could you help me ? How can I hide them or remove them?

Thaaaanks 

![capture](https://cloud.githubusercontent.com/assets/10088015/18926562/95ad26a2-85b8-11e6-99ae-76cc7013b965.PNG)

**Comment by fk** [comment]
Hi @ThibSab! Yep, I'm seeing those on http://hellodirty.com/ too, thanks for reporting this.

The thing with the "Masonite" theme is that the last time I wanted to update some of the JavaScript libraries in use (~to do a maintenance release), I was not allowed to submit the theme source code to Tumblr's "Theme Garden" – Tumblr's service complained about the minified version of the JavaScript. I tried to investigate the issue, then wrote to support – they took ages to come back, and when they did it was with a standard reply.

I might look into the issue again, but can't make any promises – sorry. :(

**Comment by fk** [comment]
@ThibSab Gave it a quick look and will prepare a new release in a few hours. 🎉

**Comment by fk** [comment]
Fixed in v0.3.1, which I just submitted to Tumblr. Will report back here once Tumblr has rolled it out.

**Comment by fk** [comment]
@ThibSab Rolled out; if you did not modify the theme HTML, then the issue should be fixed automagically! 🎉 

(If not, you can always do a fresh install from https://www.tumblr.com/theme/34822)
